name: Repro
dependencies:
  - python==3.8.3
  - r-base=4.1
  - r-tidyverse
  - pip
  - pip:
    - py-sphviewer==1.2.4
    - pandas==1.4.0
    - numpy==1.22.1
    - astropy==5.0
    - autopep8==1.5.7
    - watermark==2.2.0
    - matplotlib==3.4.3
    - astroquery==0.4.4
    - scipy==1.7.1
    - scikit-learn==0.23.1
    - seaborn==0.11.1
    - xgboost==1.3.3
    - requests==2.24.0
    - opencv-python==4.5.5.64
